const actions = {

    // timer
    SECOND_DECREMENT_TIMER: "SECOND_DECREMENT_TIMER",
    START_TIMER: "START_TIMER",
    PAUSE_TIMER: "PAUSE_TIMER",
    STOP_TIMER: "STOP_TIMER",
    FINISH_TIMER: "FINISH_TIMER",
    RESET_TIMER: "RESET_TIMER",

    // user
    ADD_USER: "ADD_USER",
    REMOVE_USER: "REMOVE_USER",
    NEXT_USER: "NEXT_USER",
    TOGGLE_USER: "TOGGLE_USER",
    CHANGE_USER_NAME: "CHANGE_USER_NAME",

    // sound
    PLAY_FINISHED_SOUND: "PLAY_FINISHED_SOUND",
    STOP_ALL_SOUNDS: "STOP_ALL_SOUNDS",
    PLAY_ELEVATOR_SOUND: "PLAY_ELEVATOR_SOUND",
};

export default actions;
